# read: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --all-features

      - name: Test
        run: cargo test --all --all-features

      - name: Run
        run: cargo run --all-features
